import { IDictionary } from "./types";

export const MIME_TYPES: IDictionary = {
  css: "text/css",
  csv: "text/csv",
  doc: "application/msword",
  docx: "application/vnd.openxmlformats-officedocument.wordprocessingml.document",
  gif: "image/gif",
  htm: "text/html",
  html: "text/html",
  ico: "image/vnd.microsoft.icon",
  jar: "application/java-archive",
  jpeg: "image/jpeg",
  jpg: "image/jpg",
  js: "text/javascript",
  ts: "application/x-typescript",
  json: "application/json",
  mp3: "audio/mpeg",
  odt: "application/vnd.oasis.opendocument.text",
  png: "image/png",
  pdf: "application/pdf",
  php: "application/x-httpd-php",
  ppt: "application/vnd.ms-powerpoint",
  rar: "application/vnd.rar",
  rtf: "application/rtf",
  sh: "application/x-sh",
  svg: "image/svg+xml",
  wav: "audio/wav",
  webm: "video/webm",
  xhtml: "application/xhtml+xml",
  xls: "application/vnd.ms-excel",
  zip: "application/zip",
  xml: "text/xml",
  txt: "text/plain",
  mp4: "video/mp4"
};

export const MIME_TYPE_ICONS: IDictionary = {
  "text/css": "mdi-language-css3",
  "text/csv": "mdi-file-delimited",
  "application/msword": "mdi-file-word",
  "application/vnd.openxmlformats-officedocument.wordprocessingml.document":
    "mdi-file-word",
  "image/gif": "mdi-file-gif-box",
  "text/html": "mdi-language-html5",
  "image/vnd.microsoft.icon": "mdi-emoticon",
  "application/java-archive": "mdi-language-java",
  "image/jpeg": "mdi-file-jpg-box",
  "image/jpg": "mdi-file-jpg-box",
  "text/javascript": "mdi-language-javascript",
  "application/x-typescript": "mdi-language-typescript",
  "application/json": "mdi-code-json",
  "audio/mpeg": "mdi-file-music",
  "application/vnd.oasis.opendocument.text": "mdi-text-box",
  "image/png": "mdi-file-image",
  "application/pdf": "mdi-file-pdf-box",
  "application/x-httpd-php": "mdi-language-php",
  "application/vnd.ms-powerpoint": "mdi-file-powerpoint",
  "application/vnd.rar": "mdi-archive",
  "application/rtf": "mdi-text-box",
  "application/x-sh": "mdi-bash",
  "image/svg+xml": "mdi-svg",
  "audio/wav": "mdi-file-music",
  "video/webm": "mdi-file-video",
  "application/xhtml+xml": "mdi-language-html5",
  "application/vnd.ms-excel": "mdi-file-excel",
  "application/zip": "mdi-archive",
  "text/xml": "mdi-xml",
  "text/plain": "mdi-text-box",
  "video/mp4": "mdi-file-video"
};

export const LANGUAGES = {
  ENGLISH: "en",
  CROATIAN: "hr"
};
